---
- hosts: all
  become: true
  tasks:

    - name: Install a .deb package from the internet using the apt module
      ansible.builtin.apt:
        name: xfce4
        state: present
    - name: Install a .deb package from the internet using the apt module
      ansible.builtin.apt:
        name: xorg
        state: present
